# Generated by Django 4.2.7 on 2023-12-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_technologystack_rename_is_admin_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.ManyToManyField(blank=True, to='user.occupation'),
        ),
    ]
