# Generated by Django 4.2.7 on 2023-12-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_occupation_technologystack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='cover_letter',
        ),
        migrations.AddField(
            model_name='user',
            name='env',
            field=models.ManyToManyField(blank=True, to='user.env'),
        ),
    ]