# Generated by Django 4.2.7 on 2024-01-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_like_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawling',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
