# Generated by Django 4.2.7 on 2024-01-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_crawling_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawling',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
