# Generated by Django 4.2.7 on 2024-01-03 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_like_user_id_like_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawling',
            name='like',
            field=models.ManyToManyField(related_name='liked_crawlings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
