# Generated by Django 4.2.7 on 2024-01-03 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_crawling_like_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawling',
            name='like',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
