# Generated by Django 4.2.7 on 2023-12-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
