# Generated by Django 4.2.7 on 2023-12-28 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_env_remove_user_cover_letter_user_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('cate', models.TextField()),
                ('env', models.TextField()),
                ('Exp_require', models.TextField()),
                ('Project_Description', models.TextField()),
                ('occupation', models.ManyToManyField(blank=True, to='user.occupation')),
                ('technology_stacks', models.ManyToManyField(blank=True, to='user.technologystack')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
