# Generated by Django 4.2.7 on 2023-12-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, unique=True)),
                ('userPw', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=100)),
                ('userAddress', models.CharField(max_length=200)),
                ('userPhone', models.CharField(max_length=20)),
                ('userEmail', models.EmailField(max_length=100)),
                ('userDate', models.DateField()),
            ],
        ),
    ]
