# Generated by Django 4.2.7 on 2023-12-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertb_groups_usertb_is_active_usertb_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertb',
            name='userDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
