# Generated by Django 4.2.7 on 2023-12-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='my_user',
        ),
    ]
