# Generated by Django 4.2.7 on 2023-12-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_occupation_remove_user_occupation_user_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='technology_stacks',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='TechnologyStack',
        ),
    ]
